### ISSUE TITLE
Parsing "éclatax"

### ISSUE THREAD

**Issue by BenoitRoux0** [BenoitRoux0/cub3D#33]
Apparemment le parsing est "éclatax" selon les dire de son créateur.

**Comment by gd-harco** [comment]
List of currently launching map that shouldn't

- [x] ./maps/bad/color_missing.cub timeout
- [x] ./maps/bad/color_none.cub timeout
- [x] ./maps/bad/empty.cub timeout
- [x] ./maps/bad/file_letter_end.cub timeout
- [x] ./maps/bad/forbidden.cub timeout
- [x] ./maps/bad/map_only.cub timeout
- [x] ./maps/bad/textures_forbidden.cub timeout
- [x] ./maps/bad/textures_missing.cub timeout
- [x] ./maps/bad/textures_none.cub timeout
- [x] ./maps/bad/textures_not_xpm.cub timeout

**Comment by BenoitRoux0** [comment]
`F -+20,   u   20,20`
work

**Comment by BenoitRoux0** [comment]
```
11111
10001
10001111111
10001110001
10000001N01
10001110001
11001  111
10001
10001
10001
10001
```
work

**Comment by gd-harco** [comment]
> ```
> 11111
> 10001
> 10001111111
> 10001110001
> 10000001N01
> 10001110001
> 11001  111
> 10001
> 10001
> 10001
> 10001
> ```
> 
> work

Expected, the player is still in an enclosed room
