### ISSUE TITLE
Comment on gere les espaces 

### ISSUE THREAD

**Issue by gd-harco** [BenoitRoux0/cub3D#4]
Ton avis sur la gestion des espaces dans les map ? Je suis d'avis de les traiter comme un sol, t'en penses quoi ?

**Comment by BenoitRoux0** [comment]
Il est indique dans le sujet que seul 6 caracteres sont admis dans une map valide.
![subshot](https://github.com/BenoitRoux0/cub3D/assets/102321220/ff80b6c5-3293-427d-9759-51ed1f4a916d)

**Comment by gd-harco** [comment]
![Capture d’écran du 2023-09-01 10-59-30](https://github.com/BenoitRoux0/cub3D/assets/93791134/d875ae52-15cb-4914-bcaa-d8662de562f4)

The map must be parsed as it looks in the file. **Spaces are a valid part of the map and are up to you to handle**. You must be able to parse any kind of map,as long as it respects the rules of the map.

**Comment by BenoitRoux0** [comment]
Je pense que le mieux serais de prendre en compte les espaces comme l'extérieur de la map.
Il faut juste voir si on accepte que le joueur spawn en dehors de la map.

**Comment by gd-harco** [comment]
> Il faut juste voir si on accepte que le joueur spawn en dehors de la map.

Le sujet dit bien qu'une map doit etre completement ferme. moi ma question est plus dans ce cas-ci :
11111
100  1
11111

L'espace est un mur ou un sol ?
